// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7XEcbx5wg6EiQ-nFyQ-gpXeOo6x8zPcY',
    appId: '1:493878936025:web:194ccc06f8d33eb33f99c8',
    messagingSenderId: '493878936025',
    projectId: 'mundacorpnotes2',
    authDomain: 'mundacorpnotes2.firebaseapp.com',
    storageBucket: 'mundacorpnotes2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_2TveyapvIs-QC7ynST9k23--Rqr7gw',
    appId: '1:493878936025:android:1d818b7aa9a6f6673f99c8',
    messagingSenderId: '493878936025',
    projectId: 'mundacorpnotes2',
    storageBucket: 'mundacorpnotes2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiiA3AYnOU-8JcMUZ8gzX0nFi-W9QliFU',
    appId: '1:493878936025:ios:2d1f2e2dc392088f3f99c8',
    messagingSenderId: '493878936025',
    projectId: 'mundacorpnotes2',
    storageBucket: 'mundacorpnotes2.firebasestorage.app',
    iosBundleId: 'com.munda.mynotes',
  );
}
